### ISSUE TITLE
你好，我用你的代码，在本地测试没有问题了，部署到服务器就报错了

### ISSUE THREAD

**Issue by 645605935** [hsu1943/thinksocketio#1]
你好，我用你的代码，在本地测试没有问题了，部署到服务器就报错了，这是什么原因造成的呢

错误信息如下：
GET http://xxx.xxx.xxx.xxx:2021/socket.io/?EIO=3&transport=polling&t=Mtu0Pv8 net::ERR_CONNECTION_TIMED_OUT

**Comment by hsu1943** [comment]
看看服务器上你请求的2021端口对外开放访问了没有？同时也要注意服务商的限制，比如阿里云的组安全策略。

**Comment by 645605935** [comment]
你好，http访问没有问题了，我配置了https访问后又报如下错误，这个是啥原因造成的呢？
polling-xhr.js:264 GET  https://xxx.xxx.xxx.xxx:2021/socket.io/?EIO=3&transport=polling&t=MtvFrrh net::ERR_TIMED_OUT

polling-xhr.js:264 GET  https://xxx.xxx.xxx.xxx:2021/socket.io/?EIO=3&transport=polling&t=MtvG6FN net::ERR_NETWORK_CHANGED

**Comment by hsu1943** [comment]
配好ssl的443端口了没？

**Comment by 645605935** [comment]
我用的是宝塔linux面板，我在宝塔面板里面配置了ssl，可以正常访问，阿里云安全组也开放443端口了，其他页面可以正常https访问，就是这个socket页面不行

**Comment by hsu1943** [comment]
前端请求地址不带端口，使用默认的443端口请求，然后使用nginx配置url转发到服务端的端口上去就好了

**Comment by 645605935** [comment]
你好，可以加个微信吗，有偿指导  微信15822836709

**Comment by hsu1943** [comment]
还有什么问题可以贴出来错误提示或者日志，周末我来看看

**Comment by donghuiing** [comment]
我在执行composer install -vvv的时候
`  - Installing topthink/framework (v5.1.18): Downloading (failed)
Downloading (failed)
Downloading (failed)    Failed to download topthink/framework from dist: The "https://files.phpcomposer.com/files/top-think/framework/833fcaf0f29f23bdceaae655f64d10c18b9bf562.zip" file could not be downloaded: failed to open stream: ▒▒▒▒Ŀ▒▒▒▒▒▒▒▒▒▒▒ܾ▒▒▒▒޷▒▒▒▒ӡ▒

    Now trying to download from source
`

**Comment by hsu1943** [comment]
参照
```html
https://beltxman.com/2554.html
```
更换一下composer的镜像
