### ISSUE TITLE
执行 php server.php    报这个错，这是什么原因？

### ISSUE THREAD

**Issue by 645605935** [hsu1943/thinksocketio#2]
你好，我部署到服务器
执行 php server.php    报这个错，这是什么原因？

[root@iZ2zebfdswir5sZ public]# php server.php
Usage: php yourfile <command> [mode]
Commands: 
start		Start worker in DEBUG mode.
		Use mode -d to start in DAEMON mode.
stop		Stop worker.
		Use mode -g to stop gracefully.
restart		Restart workers.
		Use mode -d to start in DAEMON mode.
		Use mode -g to stop gracefully.
reload		Reload codes.
		Use mode -g to reload gracefully.
status		Get worker status.
		Use mode -d to show live status.
connections	Get worker connections.

**Comment by 645605935** [comment]
已解决

**Comment by hsu1943** [comment]
你现在都搞定到线上了吗？上面这个是什么问题？我没碰到过呢

**Comment by 645605935** [comment]
嗯，现在线上运行成功了我本地是windows系统，按你说的直接运行 php server.php就可以
服务器上是linux系统，直播运行 php server.php就出现那个问题，后面加个 start就可以了


你好，可以加个微信吗？&nbsp; 微信15822836709




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hsu1943"<notifications@github.com&gt;; 
发送时间: 2019年11月2日(星期六) 上午10:25
收件人: "hsu1943/thinksocketio"<thinksocketio@noreply.github.com&gt;; 
抄送: "火星人"<645605935@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [hsu1943/thinksocketio] 执行 php server.php    报这个错，这是什么原因？ (#2)




你现在都搞定到线上了吗？上面这个是什么问题？我没碰到过呢

**Comment by BlazerYang** [comment]
> 嗯，现在线上运行成功了我本地是windows系统，按你说的直接运行 php server.php就可以 服务器上是linux系统，直播运行 php server.php就出现那个问题，后面加个 start就可以了 你好，可以加个微信吗？&nbsp; 微信15822836709
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hsu1943"<notifications@github.com&gt;; 发送时间: 2019年11月2日(星期六) 上午10:25 收件人: "hsu1943/thinksocketio"<thinksocketio@noreply.github.com&gt;; 抄送: "火星人"<645605935@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 主题: Re: [hsu1943/thinksocketio] 执行 php server.php 报这个错，这是什么原因？ (#2) 你现在都搞定到线上了吗？上面这个是什么问题？我没碰到过呢 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，请问start加在哪里呢？我直接加在`php public/server.php start`会报错
